name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # Construire l'app Angular
      - name: Build Angular app
        run: npm run build

      # Analyse du code avec SonarCloud
      # Assurez-vous que le projet est configuré sur SonarCloud et que la clé projet et l'organisation correspondent
      - name: SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=bouffonduroi
            -Dsonar.organization=campingfisa
            -Dsonar.sources=src

      # Installation des dépendances Semantic Release (déjà présentes après le npm install si déclarées dans package.json)
      # Si vous n'avez pas encore ajouté Semantic Release, assurez-vous d'ajouter au préalable dans package.json :
      # "devDependencies": {
      #   "semantic-release": "^21.0.0",
      #   "@semantic-release/changelog": "^6.0.0",
      #   "@semantic-release/git": "^11.0.0",
      #   "@semantic-release/github": "^8.0.0"
      # }
      # et un fichier de configuration comme .releaserc ou semantic-release.config.js
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Construction de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t registry.mathieu-symphorien.fr/bouffonduroi-jesterquiz:latest .
        env:
          DOCKER_BUILDKIT: 1

      # Connexion au registre Docker
      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.mathieu-symphorien.fr --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push de l'image Docker
      - name: Push Docker image
        run: |
          docker push registry.mathieu-symphorien.fr/bouffonduroi-jesterquiz:latest
